import 'package:booking_system_flutter/model/category_model.dart';
import 'package:booking_system_flutter/model/dashboard_model.dart';
import 'package:booking_system_flutter/model/service_data_model.dart';
import 'package:booking_system_flutter/app_config.dart';

/// Static mock data for demo mode (when no backend is configured)
class MockData {
  static DashboardResponse getMockDashboardResponse() {
    return DashboardResponse(
      slider: getMockSliders(),
      category: getMockCategories(),
      service: getMockServices(),
      featuredServices: getMockFeaturedServices(),
      notificationUnreadCount: 3,
    );
  }

  static List<SliderModel> getMockSliders() {
    return [
      SliderModel(
        id: 1,
        title: 'Welcome to ${AppConfig.appName}',
        description: AppConfig.appTagLine,
        sliderImage: 'assets/images/walkthrough_1.png',
        status: 1,
        type: 'service',
        typeId: 1,
      ),
      SliderModel(
        id: 2,
        title: 'Quality Services',
        description: 'Get the best services at your doorstep',
        sliderImage: 'assets/images/walkthrough_2.png',
        status: 1,
        type: 'service',
        typeId: 2,
      ),
      SliderModel(
        id: 3,
        title: 'Expert Professionals',
        description: 'Trusted and verified service providers',
        sliderImage: 'assets/images/walkthrough_3.png',
        status: 1,
        type: 'service',
        typeId: 3,
      ),
    ];
  }

  static List<CategoryData> getMockCategories() {
    return [
      CategoryData(
        id: 1,
        name: 'Category 1',
        categoryImage: AppConfig.appLogo,
        status: 1,
        isFeatured: 1,
        description: 'Category 1 services',
      ),
      CategoryData(
        id: 2,
        name: 'Category 2',
        categoryImage: AppConfig.appLogo,
        status: 1,
        isFeatured: 1,
        description: 'Category 2 services',
      ),
      CategoryData(
        id: 3,
        name: 'Category 3',
        categoryImage: AppConfig.appLogo,
        status: 1,
        isFeatured: 1,
        description: 'Category 3 services',
      ),
      CategoryData(
        id: 4,
        name: 'Home Service',
        categoryImage: AppConfig.appLogo,
        status: 1,
        isFeatured: 1,
        description: 'Professional home services',
      ),
      CategoryData(
        id: 5,
        name: 'Cleaning',
        categoryImage: AppConfig.appLogo,
        status: 1,
        isFeatured: 0,
        description: 'Professional cleaning services',
      ),
      CategoryData(
        id: 6,
        name: 'Repairs',
        categoryImage: AppConfig.appLogo,
        status: 1,
        isFeatured: 0,
        description: 'Home repair services',
      ),
    ];
  }

  static List<ServiceData> getMockServices() {
    return [
      ServiceData(
        id: 1,
        name: 'Home Cleaning',
        description: 'Professional home cleaning services for your residence. Our experts ensure a spotless and hygienic environment.',
        price: 99.99,
        categoryId: 4,
        categoryName: 'HOME SERVICES',
        attachments: ['assets/images/walkthrough_1.png'],
        serviceAttachments: ['assets/images/walkthrough_1.png'],
        status: 1,
        isFeatured: 0,
        discount: 0,
        duration: '2 hours',
        providerId: 1,
        providerName: 'Service Pro',
        providerImage: AppConfig.appLogo,
        totalRating: 4.5,
        totalReview: 128,
      ),
      ServiceData(
        id: 2,
        name: 'Consultation',
        description: 'Get expert advice from our professional consultants.',
        price: 149.99,
        categoryId: 1,
        categoryName: 'CATEGORY 1',
        attachments: ['assets/images/walkthrough_2.png'],
        serviceAttachments: ['assets/images/walkthrough_2.png'],
        status: 1,
        isFeatured: 0,
        discount: 0,
        duration: '1.5 hours',
        providerId: 2,
        providerName: 'Expert Team',
        providerImage: AppConfig.appLogo,
        totalRating: 4.8,
        totalReview: 95,
      ),
      ServiceData(
        id: 3,
        name: 'Interior Design',
        description: 'Transform your living space with our expert interior design services.',
        price: 299.99,
        categoryId: 2,
        categoryName: 'CATEGORY 2',
        attachments: ['assets/images/walkthrough_3.png'],
        serviceAttachments: ['assets/images/walkthrough_3.png'],
        status: 1,
        isFeatured: 0,
        discount: 0,
        duration: '3 hours',
        providerId: 3,
        providerName: 'Design Studio',
        providerImage: AppConfig.appLogo,
        totalRating: 4.7,
        totalReview: 67,
      ),
      ServiceData(
        id: 4,
        name: 'Premium Service',
        description: 'Our premium service offering with the best quality.',
        price: 79.99,
        categoryId: 3,
        categoryName: 'CATEGORY 3',
        attachments: ['assets/images/walkthrough_4.png'],
        serviceAttachments: ['assets/images/walkthrough_4.png'],
        status: 1,
        isFeatured: 0,
        discount: 0,
        duration: '1 hour',
        providerId: 4,
        providerName: 'Premium Team',
        providerImage: AppConfig.appLogo,
        totalRating: 4.6,
        totalReview: 142,
      ),
      ServiceData(
        id: 7,
        name: 'Deep Cleaning',
        description: 'Thorough deep cleaning service for your entire home.',
        price: 199.99,
        categoryId: 5,
        categoryName: 'CLEANING',
        attachments: ['assets/images/walkthrough_1.png'],
        serviceAttachments: ['assets/images/walkthrough_1.png'],
        status: 1,
        isFeatured: 0,
        discount: 10,
        duration: '4 hours',
        providerId: 1,
        providerName: 'Service Pro',
        providerImage: AppConfig.appLogo,
        totalRating: 4.9,
        totalReview: 203,
      ),
      ServiceData(
        id: 8,
        name: 'Home Repairs',
        description: 'Expert home repair services. From plumbing to electrical.',
        price: 89.99,
        categoryId: 6,
        categoryName: 'REPAIRS',
        attachments: ['assets/images/walkthrough_2.png'],
        serviceAttachments: ['assets/images/walkthrough_2.png'],
        status: 1,
        isFeatured: 0,
        discount: 5,
        duration: '2 hours',
        providerId: 5,
        providerName: 'Fix It Pro',
        providerImage: AppConfig.appLogo,
        totalRating: 4.4,
        totalReview: 178,
      ),
    ];
  }

  static List<ServiceData> getMockFeaturedServices() {
    return [
      ServiceData(
        id: 5,
        name: 'Premium Package',
        description: 'Complete premium package including all services.',
        price: 499.99,
        categoryId: 1,
        categoryName: 'CATEGORY 1',
        attachments: ['assets/images/walkthrough_1.png'],
        serviceAttachments: ['assets/images/walkthrough_1.png'],
        status: 1,
        isFeatured: 1,
        discount: 20,
        duration: '5 hours',
        providerId: 2,
        providerName: 'Expert Team',
        providerImage: AppConfig.appLogo,
        totalRating: 4.9,
        totalReview: 56,
      ),
      ServiceData(
        id: 6,
        name: 'Complete Transformation',
        description: 'Complete upgrade services including all categories.',
        price: 399.99,
        categoryId: 2,
        categoryName: 'CATEGORY 2',
        attachments: ['assets/images/walkthrough_3.png'],
        serviceAttachments: ['assets/images/walkthrough_3.png'],
        status: 1,
        isFeatured: 1,
        discount: 25,
        duration: '6 hours',
        providerId: 3,
        providerName: 'Design Studio',
        providerImage: AppConfig.appLogo,
        totalRating: 4.8,
        totalReview: 89,
      ),
      ServiceData(
        id: 9,
        name: 'Complete Home Care',
        description: 'All-in-one home service package including cleaning, repairs, and maintenance.',
        price: 349.99,
        categoryId: 4,
        categoryName: 'HOME SERVICES',
        attachments: ['assets/images/walkthrough_2.png'],
        serviceAttachments: ['assets/images/walkthrough_2.png'],
        status: 1,
        isFeatured: 1,
        discount: 15,
        duration: '8 hours',
        providerId: 1,
        providerName: 'Service Pro',
        providerImage: AppConfig.appLogo,
        totalRating: 4.7,
        totalReview: 112,
      ),
    ];
  }
}
