import 'package:booking_system_flutter/model/category_model.dart';
import 'package:booking_system_flutter/model/dashboard_model.dart';
import 'package:booking_system_flutter/model/service_data_model.dart';

/// Static mock data for demo mode (when no backend is configured)
/// Matches the design shown in home.jpg
class MockData {
  static DashboardResponse getMockDashboardResponse() {
    return DashboardResponse(
      slider: getMockSliders(),
      category: getMockCategories(),
      service: getMockServices(),
      featuredServices: getMockFeaturedServices(),
      notificationUnreadCount: 3,
    );
  }

  static List<SliderModel> getMockSliders() {
    return [
      SliderModel(
        id: 1,
        title: 'Welcome to Metrovibe',
        description: 'Fashion - Lifestyle - Trend - Home Services',
        sliderImage: 'assets/images/walkthrough_1.png',
        status: 1,
        type: 'service',
        typeId: 1,
      ),
      SliderModel(
        id: 2,
        title: 'Quality Services',
        description: 'Get the best services at your doorstep',
        sliderImage: 'assets/images/walkthrough_2.png',
        status: 1,
        type: 'service',
        typeId: 2,
      ),
      SliderModel(
        id: 3,
        title: 'Expert Professionals',
        description: 'Trusted and verified service providers',
        sliderImage: 'assets/images/walkthrough_3.png',
        status: 1,
        type: 'service',
        typeId: 3,
      ),
    ];
  }

  static List<CategoryData> getMockCategories() {
    return [
      CategoryData(
        id: 1,
        name: 'Fashion',
        categoryImage: 'assets/metrovibe-logo.jpg',
        status: 1,
        isFeatured: 1,
        description: 'Fashion and styling services',
      ),
      CategoryData(
        id: 2,
        name: 'Lifestyle',
        categoryImage: 'assets/metrovibe-logo.jpg',
        status: 1,
        isFeatured: 1,
        description: 'Lifestyle improvement services',
      ),
      CategoryData(
        id: 3,
        name: 'Trend',
        categoryImage: 'assets/metrovibe-logo.jpg',
        status: 1,
        isFeatured: 1,
        description: 'Stay updated with latest trends',
      ),
      CategoryData(
        id: 4,
        name: 'Home Service',
        categoryImage: 'assets/metrovibe-logo.jpg',
        status: 1,
        isFeatured: 1,
        description: 'Professional home services',
      ),
      CategoryData(
        id: 5,
        name: 'Cleaning',
        categoryImage: 'assets/metrovibe-logo.jpg',
        status: 1,
        isFeatured: 0,
        description: 'Professional cleaning services',
      ),
      CategoryData(
        id: 6,
        name: 'Repairs',
        categoryImage: 'assets/metrovibe-logo.jpg',
        status: 1,
        isFeatured: 0,
        description: 'Home repair services',
      ),
    ];
  }

  static List<ServiceData> getMockServices() {
    return [
      ServiceData(
        id: 1,
        name: 'Home Cleaning',
        description: 'Professional home cleaning services for your residence. Our experts ensure a spotless and hygienic environment.',
        price: 99.99,
        categoryId: 4,
        categoryName: 'HOME SERVICES',
        attachments: ['assets/images/walkthrough_1.png'],
        serviceAttachments: ['assets/images/walkthrough_1.png'],
        status: 1,
        isFeatured: 0,
        discount: 0,
        duration: '2 hours',
        providerId: 1,
        providerName: 'Metrovibe Pro',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.5,
        totalReview: 128,
      ),
      ServiceData(
        id: 2,
        name: 'Fashion Consultation',
        description: 'Get expert fashion advice from our professional stylists. Transform your wardrobe with personalized recommendations.',
        price: 149.99,
        categoryId: 1,
        categoryName: 'FASHION',
        attachments: ['assets/images/walkthrough_2.png'],
        serviceAttachments: ['assets/images/walkthrough_2.png'],
        status: 1,
        isFeatured: 0,
        discount: 0,
        duration: '1.5 hours',
        providerId: 2,
        providerName: 'Style Expert',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.8,
        totalReview: 95,
      ),
      ServiceData(
        id: 3,
        name: 'Interior Design',
        description: 'Transform your living space with our expert interior design services. Modern, elegant, and personalized designs.',
        price: 299.99,
        categoryId: 2,
        categoryName: 'LIFESTYLE',
        attachments: ['assets/images/walkthrough_3.png'],
        serviceAttachments: ['assets/images/walkthrough_3.png'],
        status: 1,
        isFeatured: 0,
        discount: 0,
        duration: '3 hours',
        providerId: 3,
        providerName: 'Design Studio',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.7,
        totalReview: 67,
      ),
      ServiceData(
        id: 4,
        name: 'Trending Styles',
        description: 'Stay updated with the latest fashion trends. Our stylists bring the runway to your wardrobe.',
        price: 79.99,
        categoryId: 3,
        categoryName: 'TREND',
        attachments: ['assets/images/walkthrough_4.png'],
        serviceAttachments: ['assets/images/walkthrough_4.png'],
        status: 1,
        isFeatured: 0,
        discount: 0,
        duration: '1 hour',
        providerId: 4,
        providerName: 'Trend Setter',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.6,
        totalReview: 142,
      ),
      ServiceData(
        id: 7,
        name: 'Deep Cleaning',
        description: 'Thorough deep cleaning service for your entire home. We clean every corner to perfection.',
        price: 199.99,
        categoryId: 5,
        categoryName: 'CLEANING',
        attachments: ['assets/images/walkthrough_1.png'],
        serviceAttachments: ['assets/images/walkthrough_1.png'],
        status: 1,
        isFeatured: 0,
        discount: 10,
        duration: '4 hours',
        providerId: 1,
        providerName: 'Metrovibe Pro',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.9,
        totalReview: 203,
      ),
      ServiceData(
        id: 8,
        name: 'Home Repairs',
        description: 'Expert home repair services. From plumbing to electrical, we fix everything.',
        price: 89.99,
        categoryId: 6,
        categoryName: 'REPAIRS',
        attachments: ['assets/images/walkthrough_2.png'],
        serviceAttachments: ['assets/images/walkthrough_2.png'],
        status: 1,
        isFeatured: 0,
        discount: 5,
        duration: '2 hours',
        providerId: 5,
        providerName: 'Fix It Pro',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.4,
        totalReview: 178,
      ),
    ];
  }

  static List<ServiceData> getMockFeaturedServices() {
    return [
      ServiceData(
        id: 5,
        name: 'Premium Fashion Pack',
        description: 'Complete fashion makeover package including wardrobe consultation, personal shopping, and styling session.',
        price: 499.99,
        categoryId: 1,
        categoryName: 'FASHION',
        attachments: ['assets/images/walkthrough_1.png'],
        serviceAttachments: ['assets/images/walkthrough_1.png'],
        status: 1,
        isFeatured: 1,
        discount: 20,
        duration: '5 hours',
        providerId: 2,
        providerName: 'Style Expert',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.9,
        totalReview: 56,
      ),
      ServiceData(
        id: 6,
        name: 'Lifestyle Transformation',
        description: 'Complete lifestyle upgrade services including interior design, wardrobe makeover, and personal branding.',
        price: 399.99,
        categoryId: 2,
        categoryName: 'LIFESTYLE',
        attachments: ['assets/images/walkthrough_3.png'],
        serviceAttachments: ['assets/images/walkthrough_3.png'],
        status: 1,
        isFeatured: 1,
        discount: 25,
        duration: '6 hours',
        providerId: 3,
        providerName: 'Design Studio',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.8,
        totalReview: 89,
      ),
      ServiceData(
        id: 9,
        name: 'Complete Home Care',
        description: 'All-in-one home service package including cleaning, repairs, and maintenance.',
        price: 349.99,
        categoryId: 4,
        categoryName: 'HOME SERVICES',
        attachments: ['assets/images/walkthrough_2.png'],
        serviceAttachments: ['assets/images/walkthrough_2.png'],
        status: 1,
        isFeatured: 1,
        discount: 15,
        duration: '8 hours',
        providerId: 1,
        providerName: 'Metrovibe Pro',
        providerImage: 'assets/metrovibe-logo.jpg',
        totalRating: 4.7,
        totalReview: 112,
      ),
    ];
  }
}
